### ISSUE TITLE
venv/Script/Activate.ps1: No such file or directory

### ISSUE THREAD

**Issue by ghost** [CanhhnaC/disk-scheduling-algorithms#1]
cant activate the file I don't know why I need help
![image](https://user-images.githubusercontent.com/102349049/160090633-2b0eb69d-c268-468c-8b01-502519dfbc42.png)
@CanhhnaC

**Comment by CanhhnaC** [comment]
Did you use this line 
`python3 -m venv venv`

You can find out more [here](https://stackoverflow.com/a/41972262)

If you already have it installed, instead of using git bash, you can use windows powerShell

**Comment by ghost** [comment]
Yes I already use that line
`python3 -m venv venv`
![image](https://user-images.githubusercontent.com/102349049/160241036-1b0f8c73-f000-4012-940b-aff0b4ae6659.png)

**Comment by CanhhnaC** [comment]
I see, could you use 
`venv\Scripts\Activate.ps1`

**Comment by ghost** [comment]
Same issue
![image](https://user-images.githubusercontent.com/102349049/160241334-7f31060d-e7d6-4c51-8245-d16848312e62.png)

**Comment by CanhhnaC** [comment]
No, it's a ExecutionPolicy
You can run this code with the administrator
https://stackoverflow.com/a/49112322/10903649

**Comment by ghost** [comment]
It worked!! but i have another issue :(
![image](https://user-images.githubusercontent.com/102349049/160241712-a080634f-29ba-4563-a25d-cbc377e9be8a.png)
(venv) PS C:\Users\Jamen\disk-scheduling-algorithms> pip install -r requirements.txt
Collecting numpy==1.18.2
  Using cached numpy-1.18.2.zip (5.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [191 lines of output]
      Running from numpy source directory.
      setup.py:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
        run_build = parse_setuppy_commands()
      C:\Users\Jamen\AppData\Local\Temp\pip-install-4xu5021d\numpy_59f3e253dc2a421ea847c91da63ae4f5\tools\cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        required_version = LooseVersion('0.29.14')
      C:\Users\Jamen\AppData\Local\Temp\pip-install-4xu5021d\numpy_59f3e253dc2a421ea847c91da63ae4f5\tools\cythonize.py:77: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(cython_version) < required_version:
      Processing numpy/random\_bounded_integers.pxd.in
      Processing numpy/random\mtrand.pyx
      Processing numpy/random\_bit_generator.pyx
      Processing numpy/random\_bounded_integers.pyx.in
      Processing numpy/random\_common.pyx
      Processing numpy/random\_generator.pyx
      Processing numpy/random\_mt19937.pyx
      Processing numpy/random\_pcg64.pyx
      Processing numpy/random\_philox.pyx
      Processing numpy/random\_sfc64.pyx
      Cythonizing sources
      blas_opt_info:
      blas_mkl_info:
      No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      customize MSVCCompiler
        libraries mkl_rt not found in ['C:\\Users\\Jamen\\disk-scheduling-algorithms\\venv\\lib', 'C:\\']
        NOT AVAILABLE

      blis_info:
        libraries blis not found in ['C:\\Users\\Jamen\\disk-scheduling-algorithms\\venv\\lib', 'C:\\']
        NOT AVAILABLE

      openblas_info:
        libraries openblas not found in ['C:\\Users\\Jamen\\disk-scheduling-algorithms\\venv\\lib', 'C:\\']
      get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
      customize GnuFCompiler
      Could not locate executable g77
      Could not locate executable f77
      customize IntelVisualFCompiler
      Could not locate executable ifort
      Could not locate executable ifl
      customize AbsoftFCompiler
      Could not locate executable f90
      customize CompaqVisualFCompiler
      Could not locate executable DF
      customize IntelItaniumVisualFCompiler
      Could not locate executable efl
      customize Gnu95FCompiler
      Could not locate executable gfortran
      Could not locate executable f95
      customize G95FCompiler
      Could not locate executable g95
      customize IntelEM64VisualFCompiler
      customize IntelEM64TFCompiler
      Could not locate executable efort
      Could not locate executable efc
      customize PGroupFlangCompiler
      Could not locate executable flang
      don't know how to compile Fortran code on platform 'nt'
        NOT AVAILABLE

      atlas_3_10_blas_threads_info:
      Setting PTATLAS=ATLAS
        libraries tatlas not found in ['C:\\Users\\Jamen\\disk-scheduling-algorithms\\venv\\lib', 'C:\\']
        NOT AVAILABLE

      atlas_3_10_blas_info:
        libraries satlas not found in ['C:\\Users\\Jamen\\disk-scheduling-algorithms\\venv\\lib', 'C:\\']
        NOT AVAILABLE

      atlas_blas_threads_info:
      Setting PTATLAS=ATLAS
        libraries ptf77blas,ptcblas,atlas not found in ['C:\\Users\\Jamen\\disk-scheduling-algorithms\\venv\\lib', 'C:\\']
        NOT AVAILABLE

      atlas_blas_info:
        libraries f77blas,cblas,atlas not found in ['C:\\Users\\Jamen\\disk-scheduling-algorithms\\venv\\lib', 'C:\\']
        NOT AVAILABLE

      accelerate_info:
        NOT AVAILABLE

      C:\Users\Jamen\AppData\Local\Temp\pip-install-4xu5021d\numpy_59f3e253dc2a421ea847c91da63ae4f5\numpy\distutils\system_info.py:1896: UserWarning:
          Optimized (vendor) Blas libraries are not found.
          Falls back to netlib Blas library which has worse performance.
          A better performance should be easily gained by switching
          Blas library.
        if self._calc_info(blas):
      blas_info:
        libraries blas not found in ['C:\\Users\\Jamen\\disk-scheduling-algorithms\\venv\\lib', 'C:\\']
        NOT AVAILABLE

      C:\Users\Jamen\AppData\Local\Temp\pip-install-4xu5021d\numpy_59f3e253dc2a421ea847c91da63ae4f5\numpy\distutils\system_info.py:1896: UserWarning:
          Blas (http://www.netlib.org/blas/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [blas]) or by setting
          the BLAS environment variable.
        if self._calc_info(blas):
      blas_src_info:
        NOT AVAILABLE

      C:\Users\Jamen\AppData\Local\Temp\pip-install-4xu5021d\numpy_59f3e253dc2a421ea847c91da63ae4f5\numpy\distutils\system_info.py:1896: UserWarning:
          Blas (http://www.netlib.org/blas/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [blas_src]) or by setting
          the BLAS_SRC environment variable.
        if self._calc_info(blas):
        NOT AVAILABLE

      non-existing path in 'numpy\\distutils': 'site.cfg'
      lapack_opt_info:
      lapack_mkl_info:
        libraries mkl_rt not found in ['C:\\Users\\Jamen\\disk-scheduling-algorithms\\venv\\lib', 'C:\\']
        NOT AVAILABLE

      openblas_lapack_info:
        libraries openblas not found in ['C:\\Users\\Jamen\\disk-scheduling-algorithms\\venv\\lib', 'C:\\']
        NOT AVAILABLE

      openblas_clapack_info:
        libraries openblas,lapack not found in ['C:\\Users\\Jamen\\disk-scheduling-algorithms\\venv\\lib', 'C:\\']
        NOT AVAILABLE

      flame_info:
        libraries flame not found in ['C:\\Users\\Jamen\\disk-scheduling-algorithms\\venv\\lib', 'C:\\']
        NOT AVAILABLE

      atlas_3_10_threads_info:
      Setting PTATLAS=ATLAS
        libraries lapack_atlas not found in C:\Users\Jamen\disk-scheduling-algorithms\venv\lib
        libraries tatlas,tatlas not found in C:\Users\Jamen\disk-scheduling-algorithms\venv\lib
        libraries lapack_atlas not found in C:\
        libraries tatlas,tatlas not found in C:\
      <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
        NOT AVAILABLE

      atlas_3_10_info:
        libraries lapack_atlas not found in C:\Users\Jamen\disk-scheduling-algorithms\venv\lib
        libraries satlas,satlas not found in C:\Users\Jamen\disk-scheduling-algorithms\venv\lib
        libraries lapack_atlas not found in C:\
        libraries satlas,satlas not found in C:\
      <class 'numpy.distutils.system_info.atlas_3_10_info'>
        NOT AVAILABLE

      atlas_threads_info:
      Setting PTATLAS=ATLAS
        libraries lapack_atlas not found in C:\Users\Jamen\disk-scheduling-algorithms\venv\lib
        libraries ptf77blas,ptcblas,atlas not found in C:\Users\Jamen\disk-scheduling-algorithms\venv\lib
        libraries lapack_atlas not found in C:\
        libraries ptf77blas,ptcblas,atlas not found in C:\
      <class 'numpy.distutils.system_info.atlas_threads_info'>
        NOT AVAILABLE

      atlas_info:
        libraries lapack_atlas not found in C:\Users\Jamen\disk-scheduling-algorithms\venv\lib
        libraries f77blas,cblas,atlas not found in C:\Users\Jamen\disk-scheduling-algorithms\venv\lib
        libraries lapack_atlas not found in C:\
        libraries f77blas,cblas,atlas not found in C:\
      <class 'numpy.distutils.system_info.atlas_info'>
        NOT AVAILABLE

      lapack_info:
        libraries lapack not found in ['C:\\Users\\Jamen\\disk-scheduling-algorithms\\venv\\lib', 'C:\\']
        NOT AVAILABLE

      C:\Users\Jamen\AppData\Local\Temp\pip-install-4xu5021d\numpy_59f3e253dc2a421ea847c91da63ae4f5\numpy\distutils\system_info.py:1730: UserWarning:
          Lapack (http://www.netlib.org/lapack/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [lapack]) or by setting
          the LAPACK environment variable.
        return getattr(self, '_calc_info_{}'.format(name))()
      lapack_src_info:
        NOT AVAILABLE

      C:\Users\Jamen\AppData\Local\Temp\pip-install-4xu5021d\numpy_59f3e253dc2a421ea847c91da63ae4f5\numpy\distutils\system_info.py:1730: UserWarning:
          Lapack (http://www.netlib.org/lapack/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [lapack_src]) or by setting
          the LAPACK_SRC environment variable.
        return getattr(self, '_calc_info_{}'.format(name))()
        NOT AVAILABLE

      C:\Users\Jamen\AppData\Local\Temp\pip-build-env-xaxl48dr\overlay\Lib\site-packages\setuptools\_distutils\dist.py:275: UserWarning: Unknown distribution option: 'define_macros'
        warnings.warn(msg)
      running dist_info
      running build_src
      build_src
      building py_modules sources
      creating build
      creating build\src.win-amd64-3.9
      creating build\src.win-amd64-3.9\numpy
      creating build\src.win-amd64-3.9\numpy\distutils
      building library "npymath" sources
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(venv) PS C:\Users\Jamen\disk-scheduling-algorithms> python3 ./handle.py
Traceback (most recent call last):
  File "C:\Users\Jamen\disk-scheduling-algorithms\handle.py", line 1, in <module>
    from PyQt5 import QtGui, QtWidgets, QtCore, uic
ModuleNotFoundError: No module named 'PyQt5'
(venv) PS C:\Users\Jamen\disk-scheduling-algorithms>

**Comment by CanhhnaC** [comment]
Did you use python ver 3.7

**Comment by JaimenSingh** [comment]
I'm using ver 3.9 will that not work

**Comment by CanhhnaC** [comment]
can you downgrade python 3.9 to 3.7?

**Comment by ghost** [comment]
I got it working thank you so much I used python ver 3.7 then i changed
`python3 -m venv venv`
to
`python -m venv venv`

also for
`python3 ./handle.py`
to
`python ./handle.py`

**Comment by CanhhnaC** [comment]
you're welcome.
